name: Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Functions dependencies
      run: |
        cd functions
        npm ci
        cd ..
        
    - name: Build application
      run: npm run build
      
    - name: Run linter
      run: npm run lint
      continue-on-error: true
      
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HEARTLINK_F4FTQ }}'
        projectId: heartlink-f4ftq
        channelId: live
        
    - name: Deploy Functions and Rules
      if: github.ref == 'refs/heads/main'
      run: |
        npm install -g firebase-tools
        firebase deploy --only functions,storage,database --project heartlink-f4ftq --token ${{ secrets.FIREBASE_TOKEN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}